# Generated by Django 3.0.4 on 2020-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=30)),
                ('clientID', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('jobtitle', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('officephone', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=30)),
                ('prefix', models.CharField(max_length=30)),
            ],
        ),
    ]
